import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { network } from 'hardhat'
import { parseEther, zeroAddress } from 'viem'

const connection = await network.create()
const { viem } = connection

async function fixture() {
  const [owner, executor, stranger] = await viem.getWalletClients()
  const tokenIn = await viem.deployContract('MockToken', ['Input', 'IN'])
  const tokenOut = await viem.deployContract('MockToken', ['Output', 'OUT'])
  const adapter = await viem.deployContract('MockSwapAdapter')
  const vault = await viem.deployContract('AgentVault', [owner.account.address, 1n, executor.account.address])
  return { owner, executor, stranger, tokenIn, tokenOut, adapter, vault }
}

describe('AgentVault', () => {
  it('creates at most one vault per ERC-8004 identity and only for its current owner', async () => {
    const [owner, executor, stranger] = await viem.getWalletClients()
    const registry = await viem.deployContract('MockIdentityRegistry')
    await registry.write.setOwner([42n, owner.account.address])
    const factory = await viem.deployContract('AgentVaultFactory', [registry.address])
    await assert.rejects(factory.write.createVault([42n, executor.account.address], { account: stranger.account }))
    await factory.write.createVault([42n, executor.account.address], { account: owner.account })
    const vaultAddress = await factory.read.vaultOf([42n])
    assert.notEqual(vaultAddress, zeroAddress)
    await assert.rejects(factory.write.createVault([42n, executor.account.address], { account: owner.account }))
  })

  it('keeps vault funds with their creator and gives each later identity owner a separate current vault', async () => {
    const [owner, executor, nextOwner] = await viem.getWalletClients()
    const registry = await viem.deployContract('MockIdentityRegistry')
    await registry.write.setOwner([43n, owner.account.address])
    const factory = await viem.deployContract('AgentVaultFactory', [registry.address])
    await factory.write.createVault([43n, executor.account.address], { account: owner.account })
    const firstVaultAddress = await factory.read.vaultOf([43n])
    const firstVault = await viem.getContractAt('AgentVault', firstVaultAddress)
    await registry.write.setOwner([43n, nextOwner.account.address])
    assert.equal(await factory.read.vaultOf([43n]), zeroAddress)
    await assert.rejects(firstVault.write.setPaused([true], { account: nextOwner.account }))
    await firstVault.write.setPaused([true], { account: owner.account })
    await factory.write.createVault([43n, executor.account.address], { account: nextOwner.account })
    const secondVaultAddress = await factory.read.vaultOf([43n])
    assert.notEqual(secondVaultAddress.toLowerCase(), firstVaultAddress.toLowerCase())
    await registry.write.setOwner([43n, owner.account.address])
    assert.equal((await factory.read.vaultOf([43n])).toLowerCase(), firstVaultAddress.toLowerCase())
  })

  it('lets anyone fund it but only the owner withdraw', async () => {
    const { owner, stranger, vault } = await fixture()
    await stranger.sendTransaction({ to: vault.address, value: parseEther('1') })
    const publicClient = await viem.getPublicClient()
    assert.equal(await publicClient.getBalance({ address: vault.address }), parseEther('1'))
    await assert.rejects(vault.write.withdrawNative([stranger.account.address, parseEther('0.1')], { account: stranger.account }))
    await vault.write.withdrawNative([owner.account.address, parseEther('1')], { account: owner.account })
    assert.equal(await publicClient.getBalance({ address: vault.address }), 0n)
  })

  it('allows only the executor to use an owner-approved adapter within per-token limits', async () => {
    const { owner, executor, stranger, tokenIn, tokenOut, adapter, vault } = await fixture()
    await tokenIn.write.mint([vault.address, 1_000n])
    await tokenOut.write.mint([adapter.address, 1_000n])
    await vault.write.setAdapter([adapter.address, true], { account: owner.account })
    await vault.write.setOutputToken([tokenOut.address, true], { account: owner.account })
    await vault.write.setPolicy([tokenIn.address, 200n, 300n], { account: owner.account })
    await assert.rejects(vault.write.executeSwap([adapter.address, tokenIn.address, tokenOut.address, 0, 100n, 90n, BigInt(Math.floor(Date.now()/1000)+300)], { account: stranger.account }))
    await vault.write.executeSwap([adapter.address, tokenIn.address, tokenOut.address, 0, 100n, 90n, BigInt(Math.floor(Date.now()/1000)+300)], { account: executor.account })
    assert.equal(await tokenOut.read.balanceOf([vault.address]), 90n)
    await assert.rejects(vault.write.executeSwap([adapter.address, tokenIn.address, tokenOut.address, 0, 201n, 1n, BigInt(Math.floor(Date.now()/1000)+300)], { account: executor.account }))
  })

  it('binds adapter execution to the same amount and minimum output enforced by the vault', async () => {
    const { owner, executor, tokenIn, tokenOut, adapter, vault } = await fixture()
    await tokenIn.write.mint([vault.address, 1_000n])
    await tokenOut.write.mint([adapter.address, 1_000n])
    await vault.write.setAdapter([adapter.address, true], { account: owner.account })
    await vault.write.setOutputToken([tokenOut.address, true], { account: owner.account })
    await vault.write.setPolicy([tokenIn.address, 200n, 300n], { account: owner.account })
    const deadline = BigInt(Math.floor(Date.now()/1000)+300)
    await vault.write.executeSwap([adapter.address, tokenIn.address, tokenOut.address, 0, 100n, 90n, deadline], { account: executor.account })
    assert.equal(await adapter.read.lastAmountIn(), 100n)
    assert.equal(await adapter.read.lastMinOut(), 90n)
    assert.equal((await adapter.read.lastRecipient()).toLowerCase(), vault.address.toLowerCase())
  })

  it('rejects an output token that the owner has not allowlisted', async () => {
    const { owner, executor, tokenIn, tokenOut, adapter, vault } = await fixture()
    await tokenIn.write.mint([vault.address, 1_000n])
    await tokenOut.write.mint([adapter.address, 1_000n])
    await vault.write.setAdapter([adapter.address, true], { account: owner.account })
    await vault.write.setPolicy([tokenIn.address, 200n, 300n], { account: owner.account })
    await assert.rejects(vault.write.executeSwap([adapter.address, tokenIn.address, tokenOut.address, 0, 100n, 90n, BigInt(Math.floor(Date.now()/1000)+300)], { account: executor.account }))
  })

  it('rejects zero minimum output and non-contract token policies', async () => {
    const { owner, executor, stranger, tokenIn, tokenOut, adapter, vault } = await fixture()
    await tokenIn.write.mint([vault.address, 1_000n])
    await tokenOut.write.mint([adapter.address, 1_000n])
    await vault.write.setAdapter([adapter.address, true], { account: owner.account })
    await vault.write.setOutputToken([tokenOut.address, true], { account: owner.account })
    await vault.write.setPolicy([tokenIn.address, 200n, 300n], { account: owner.account })
    await assert.rejects(vault.write.setPolicy([stranger.account.address, 1n, 1n], { account: owner.account }))
    await assert.rejects(vault.write.executeSwap([adapter.address, tokenIn.address, tokenOut.address, 0, 100n, 0n, BigInt(Math.floor(Date.now()/1000)+300)], { account: executor.account }))
  })

  it('rejects fee-on-transfer inputs and rolls back balances and budget', async () => {
    const { owner, executor, tokenOut, adapter, vault } = await fixture()
    const feeToken = await viem.deployContract('MockFeeToken', ['Fee', 'FEE'])
    await feeToken.write.mint([vault.address, 1_000n])
    await tokenOut.write.mint([adapter.address, 1_000n])
    await vault.write.setAdapter([adapter.address, true], { account: owner.account })
    await vault.write.setOutputToken([tokenOut.address, true], { account: owner.account })
    await vault.write.setPolicy([feeToken.address, 200n, 300n], { account: owner.account })
    await assert.rejects(vault.write.executeSwap([adapter.address, feeToken.address, tokenOut.address, 0, 100n, 90n, BigInt(Math.floor(Date.now()/1000)+300)], { account: executor.account }))
    assert.equal(await feeToken.read.balanceOf([vault.address]), 1_000n)
    assert.equal((await vault.read.policies([feeToken.address]))[2], 0n)
  })

  it('enforces minimum output, pause, deadline, revocation, and native-token budgets', async () => {
    const { owner, executor, tokenOut, adapter, vault } = await fixture()
    await owner.sendTransaction({ to: vault.address, value: parseEther('1') })
    await tokenOut.write.mint([adapter.address, 1_000n])
    await vault.write.setAdapter([adapter.address, true], { account: owner.account })
    await vault.write.setOutputToken([tokenOut.address, true], { account: owner.account })
    await vault.write.setPolicy([zeroAddress, parseEther('0.2'), parseEther('0.3')], { account: owner.account })
    const deadline = BigInt(Math.floor(Date.now()/1000)+300)
    await adapter.write.setOutput([10n])
    const publicClient = await viem.getPublicClient()
    const beforeFailure = await publicClient.getBalance({ address: vault.address })
    await assert.rejects(vault.write.executeSwap([adapter.address, zeroAddress, tokenOut.address, 0, parseEther('0.1'), 11n, deadline], { account: executor.account }))
    assert.equal(await publicClient.getBalance({ address: vault.address }), beforeFailure)
    assert.equal((await vault.read.policies([zeroAddress]))[2], 0n)
    await assert.rejects(vault.write.executeSwap([adapter.address, zeroAddress, tokenOut.address, 0, parseEther('0.1'), 1n, 1n], { account: executor.account }))
    await vault.write.setAdapter([adapter.address, false], { account: owner.account })
    await assert.rejects(vault.write.executeSwap([adapter.address, zeroAddress, tokenOut.address, 0, parseEther('0.1'), 1n, deadline], { account: executor.account }))
    await vault.write.setAdapter([adapter.address, true], { account: owner.account })
    await vault.write.setPaused([true], { account: owner.account })
    await assert.rejects(vault.write.executeSwap([adapter.address, zeroAddress, tokenOut.address, 0, parseEther('0.1'), 1n, deadline], { account: executor.account }))
    await vault.write.setExecutor([zeroAddress], { account: owner.account })
    assert.equal(await vault.read.executor(), zeroAddress)
  })

  it('enforces the cumulative daily budget', async () => {
    const { owner, executor, tokenIn, tokenOut, adapter, vault } = await fixture()
    await tokenIn.write.mint([vault.address, 1_000n])
    await tokenOut.write.mint([adapter.address, 1_000n])
    await vault.write.setAdapter([adapter.address, true], { account: owner.account })
    await vault.write.setOutputToken([tokenOut.address, true], { account: owner.account })
    await vault.write.setPolicy([tokenIn.address, 200n, 300n], { account: owner.account })
    const deadline = BigInt(Math.floor(Date.now()/1000)+300)
    await vault.write.executeSwap([adapter.address, tokenIn.address, tokenOut.address, 0, 150n, 1n, deadline], { account: executor.account })
    await vault.write.executeSwap([adapter.address, tokenIn.address, tokenOut.address, 0, 150n, 1n, deadline], { account: executor.account })
    await assert.rejects(vault.write.executeSwap([adapter.address, tokenIn.address, tokenOut.address, 0, 1n, 1n, deadline], { account: executor.account }))
    assert.equal((await vault.read.policies([tokenIn.address]))[2], 300n)
  })

  it('routes an exact ERC20 input through the fixed Pancake v3 router and returns output only to the vault', async () => {
    const [owner, executor] = await viem.getWalletClients()
    const registry = await viem.deployContract('MockIdentityRegistry')
    await registry.write.setOwner([7n, owner.account.address])
    const factory = await viem.deployContract('AgentVaultFactory', [registry.address])
    await factory.write.createVault([7n, executor.account.address], { account: owner.account })
    const vaultAddress = await factory.read.vaultOf([7n])
    const vault = await viem.getContractAt('AgentVault', vaultAddress)
    const tokenIn = await viem.deployContract('MockToken', ['Input', 'IN'])
    const tokenOut = await viem.deployContract('MockToken', ['Output', 'OUT'])
    const wrapped = await viem.deployContract('MockWrappedNative')
    const router = await viem.deployContract('MockPancakeV3Router')
    const adapter = await viem.deployContract('PancakeV3Adapter', [factory.address, router.address, wrapped.address])
    await tokenIn.write.mint([vault.address, 1_000n])
    await tokenOut.write.mint([router.address, 1_000n])
    await vault.write.setAdapter([adapter.address, true], { account: owner.account })
    await vault.write.setOutputToken([tokenOut.address, true], { account: owner.account })
    await vault.write.setPolicy([tokenIn.address, 200n, 300n], { account: owner.account })
    const deadline = BigInt(Math.floor(Date.now()/1000)+300)
    await vault.write.executeSwap([adapter.address, tokenIn.address, tokenOut.address, 2500, 100n, 95n, deadline], { account: executor.account })
    assert.equal(await tokenOut.read.balanceOf([vault.address]), 95n)
    assert.equal(await tokenIn.read.balanceOf([adapter.address]), 0n)
    assert.equal(await tokenIn.read.allowance([adapter.address, router.address]), 0n)
  })

  it('wraps a policy-bounded native BNB input before routing it to the fixed router', async () => {
    const [owner, executor, stranger] = await viem.getWalletClients()
    const registry = await viem.deployContract('MockIdentityRegistry')
    await registry.write.setOwner([8n, owner.account.address])
    const factory = await viem.deployContract('AgentVaultFactory', [registry.address])
    await factory.write.createVault([8n, executor.account.address], { account: owner.account })
    const vaultAddress = await factory.read.vaultOf([8n])
    const vault = await viem.getContractAt('AgentVault', vaultAddress)
    const tokenOut = await viem.deployContract('MockToken', ['Output', 'OUT'])
    const wrapped = await viem.deployContract('MockWrappedNative')
    const router = await viem.deployContract('MockPancakeV3Router')
    const adapter = await viem.deployContract('PancakeV3Adapter', [factory.address, router.address, wrapped.address])
    await owner.sendTransaction({ to: vault.address, value: parseEther('1') })
    await tokenOut.write.mint([router.address, 1_000n])
    await vault.write.setAdapter([adapter.address, true], { account: owner.account })
    await vault.write.setOutputToken([tokenOut.address, true], { account: owner.account })
    await vault.write.setPolicy([zeroAddress, parseEther('0.2'), parseEther('0.3')], { account: owner.account })
    const deadline = BigInt(Math.floor(Date.now()/1000)+300)
    await assert.rejects(adapter.write.swap([zeroAddress, tokenOut.address, 2500, parseEther('0.1'), 95n, deadline], { account: stranger.account, value: parseEther('0.1') }))
    await vault.write.executeSwap([adapter.address, zeroAddress, tokenOut.address, 2500, parseEther('0.1'), 95n, deadline], { account: executor.account })
    assert.equal(await tokenOut.read.balanceOf([vault.address]), 95n)
    assert.equal(await wrapped.read.balanceOf([adapter.address]), 0n)
  })
})
